server:
  port: 80
spring:
  main:
    web-application-type: reactive
    banner-mode: off
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7071        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth_service

        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://localhost:7072
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user_service

        - id: company-service
          predicates:
            - Path=/company/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7073        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/company_service

        - id: payment-service
          predicates:
            - Path=/payment/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7074        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/payment_service

        - id: comment-service
          predicates:
            - Path=/comment/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7076        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/comment_service

        - id: permission-service
          predicates:
            - Path=/permission/**                 # localhost/auth/find_all - localhost/api/v1/auth/find_all
          uri: http://localhost:7077        #localhost:7071/api/v1/auth/find_all
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/permission_service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}   #regex yazımı