server:
  port: 7075
spring:
  main:
    banner-mode: off
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  mail-queue: queue-mail