server:
  port: 7072
spring:
  main:
    banner-mode: off
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 123456789
  data:
    mongodb:
      host: localhost
      port: 27017
      username: mongo
      password: root
      database: ECommerceUser
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

rabbitmq:
  register-queue: register-queue
  activation-queue: queue-activation
  register-elastic-queue: register-elastic-queue
  register-elastic-binding: register-elastic-binding
  user-exchange: exchange-user



